//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btlweb.cms.Admin.Sanpham.Danhgiaphong
{


    public partial class danhgiaControl
    {
    }
}
